### ISSUE TITLE
Türkçe çeviri

### ISSUE THREAD

**Issue by skuran** [snmzclk/OCS-Turkish-Language-Translation#1]
Merhaba, emeğinize sağlık. Resmi sitede olmasa bile burada çeviri dosyalarını bulabiliyoruz. Fakat 2.3.6 sürümünde registry/locales.xml dosyasına Türkçe'yi ekleyip sizin çeviri dosyalarını ilgili klasörlere kopyaladığımda ve varsayılan dili Türkçe ile değiştirip kaydettiğimde 500 hatası alıyorum ve artık siteye erişilemiyor veritabanından default_locale en_US yapsam bile durum değişmiyor. Bu durumla karşılaşan oldu mu?

**Comment by snmzclk** [comment]
Merhaba,
Bu hata ile karşılaştım.  Sunucu kurulumunun dili ile ilgili bir sorun. Şu paylaşımdaki çözümü bir deneyin:
http://www.sonmezcelik.net/2018/01/ojs-turkce-dil-secenegi-hatas.html
Eğer bu sorununuzu çözmez ise aşağıdaki uygulamayı yapın.

registry/locales.xml dosyasında kodlama şu şekilde olmalı:
<locale key="tr_TR" complete="true"  name="Türkçe" iso639-2b="tur" iso639-3="tur" />
yüklemeden, dil dosyalarını attıktan sonra Cache dosyalarını bir temizleyin? Ayrıca Diğer dil dosyalarındaki  locale name kısmının aşağıdaki gibi olduğuna dikkat edin. 
<locale name="tr_TR" full_name="Türkçe">

**Comment by skuran** [comment]
[http://www.sonmezcelik.net/2012/03/ojs-236-surumu-turkce-dil-hatas.html](url)
Eski bir hataymış. Yukarıdaki sayfayı takip edince çözüldü. Teşekkürler.
